package com.bookingsystem.model;

import java.time.LocalTime;

/**
 * A single candidate appointment window on a given day, generated by the
 * {@link com.bookingsystem.service.SlotGenerator}. Purely a value holder;
 * it does not know whether it has actually been booked - the generator
 * only returns slots that are already free.
 */
public class TimeSlot {

    private final LocalTime start;
    private final LocalTime end;

    public TimeSlot(LocalTime start, LocalTime end) {
        this.start = start;
        this.end = end;
    }

    public LocalTime getStart() {
        return start;
    }

    public LocalTime getEnd() {
        return end;
    }

    @Override
    public String toString() {
        return start + " - " + end;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TimeSlot)) return false;
        TimeSlot other = (TimeSlot) o;
        return start.equals(other.start) && end.equals(other.end);
    }

    @Override
    public int hashCode() {
        return start.hashCode() * 31 + end.hashCode();
    }
}
